# Generated by Django 5.2.2 on 2025-06-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Duplo', 'Duplo'), ('Luxo', 'Luxo')], max_length=20)),
                ('capacidade', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservado', 'Reservado')], default='Disponível', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospede_nome', models.CharField(max_length=100)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.quarto')),
                ('reservado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
